server:
  port: 8080

spring:
  application:
    name: "blog"
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:mem:workdb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  sql:
    init:
      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,hystrix.stream
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

upload:
  path:
    media: ${UPLOAD_PATH_MEDIA:/tmp/webFiles}