spring:
  data:
    mongodb:
      host: localhost
      database: test

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.ghost.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local